version: '3'
services:
  node1:
    image: webz-001
    container_name: webz-001
    environment:
      - NODE_ID=1
      - NODE_ADDR=webz-001
      - PEER_NODES=webz-002,webz-003
    ports:
      - "8081:80"  
    networks:
      cluster_network:
        ipv4_address: 192.168.16.10
    command: /bin/bash floating_ip.sh
    cap_add:
      - NET_ADMIN
      - NET_RAW

  node2:
    image: webz-001
    container_name: webz-002
    environment:
      - NODE_ID=2
      - NODE_ADDR=webz-002
      - PEER_NODES=webz-001,webz-003
    ports:
      - "8082:80"  
    networks:
      cluster_network:
        ipv4_address: 192.168.16.11
    cap_add:
      - NET_ADMIN
      - NET_RAW
        
  node3:
    image: webz-001
    container_name: webz-003
    environment:
      - NODE_ID=3
      - NODE_ADDR=webz-003
      - PEER_NODES=webz-001,webz-002
    ports:
      - "8083:80"  
    networks:
      cluster_network:
        ipv4_address: 192.168.16.12
    cap_add:
      - NET_ADMIN
      - NET_RAW
        
networks:
  cluster_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.16.0/20

