FROM ubuntu:18.04


RUN apt-get update && \
    apt-get install -y wget openjdk-11-jdk curl

ENV JENKINS_HOME=/var/jenkins_home
ENV JENKINS_PORT=8080

RUN mkdir -p $JENKINS_HOME

RUN mkdir -p /logs && \
    chown -R 1000:1000 /logs

RUN wget http://mirrors.jenkins.io/war-stable/latest/jenkins.war -O /usr/local/bin/jenkins.war


RUN apt-get update && \
    apt-get install -y \
    curl \
    gnupg \
    lsb-release

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

RUN echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io


EXPOSE $JENKINS_PORT

CMD ["java", "-jar", "/usr/local/bin/jenkins.war"]
